### ISSUE TITLE
gha no longer works since latest Docker Desktop release

### ISSUE THREAD

**Issue by joe0BAB** [docker/desktop-action#5]
Unfortunately, since latest Docker Desktop release this gha no longer seems to work. It consistently get's stuck at

```
Run until docker ps; do echo "docker not ready, sleep 10 s and try again"; sleep 10; done
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
docker not ready, sleep 10 s and try again
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
docker not ready, sleep 10 s and try again
```

and never get's out of this loop

**Comment by benja-M-1** [comment]
Here are some examples of the issue:
- https://github.com/docker/extensions-submissions/actions/runs/6392380662/job/17349535350
- https://github.com/docker/extensions-submissions/actions/runs/6354673175/job/17265368980

I believe the issue is rather related to Docker Desktop itself rather than the action. If we add a parameter to the action to specify the version of DD to use so that we can downgrade if needed.

**Comment by benja-M-1** [comment]
The problem is that Docker Desktop needs virtualisation to be enabled. It seems that the machine on which the action runs randomly have it. We saw the action failing and passing on different runs in the same repo.
As explained in [this blog post](https://github.blog/changelog/2023-02-23-hardware-accelerated-android-virtualization-on-actions-windows-and-linux-larger-hosted-runners/) only large Linux runners have it. So we made this action runnable on linux in [v0.2.0](https://github.com/docker/desktop-action/releases/tag/v0.2.0). However, the users must use large Linux runners.

It is not ideal until GitHub Action supports virtualisation on every runner 🤞
